import BackButton from "./BackButton.js";

export default function DisplayText({
  className,
  displayList,
  setDisplayList,
  selectedSubOption,
  setSelectedSubOption,
}) {
  return (
    <div className={className}>
      <div className="contentContainer">
        {selectedSubOption.subOptionKey === "sub1" &&
          selectedSubOption.parentTitle ===
            "Admission Process for English Programs" && (
            <p>
              Admission calendar: Online registration:02.05.2023-30.06.2023
              Session I: File competition results:10.07.2023 Session II: Online
              registration:01.08.2023-25.08.2023 File competition
              results:04.09.2023
            </p>
          )}
        {selectedSubOption.subOptionKey === "sub2" &&
          selectedSubOption.parentTitle ===
            "Admission Process for English Programs" && (
            <p>
              The candidates who have passed the Baccalaureate examination in
              the sessions corresponding to the school year 2022-2023 may
              submit, instead of the Baccalaureate / High-School Diploma, a
              certificate issued by the high school, obligatorily specifying the
              grade point averages obtained during the years of study, the
              validity term of the certificate and the fact that the
              Baccalaureate diploma was not issued - certified translation into
              Romanian;
            </p>
          )}
        {selectedSubOption.subOptionKey === "sub3" &&
          selectedSubOption.parentTitle ===
            "Admission Process for English Programs" && (
            <p>
              1. Annex 1 (will be automatically generated by the platform at the
              time of application); 2. Annex 2 (will be automatically generated
              by the platform at the time of application); 3. A language
              proficiency certificate minimum B2 level, internationally
              recognized, not older than 2 years, or the certificate of
              linguistic competency, obtained from the Discipline of Modern
              Languages, the Faculty of Medicine UMPCD, within our university
              (ANNEX 3); The citizens who have completed the high school studies
              in an educational institution in which the language of instruction
              is English or who have obtained at least a B2 level as part of the
              Baccalaureate examination are exempted from providing the language
              proficiency certificate; 4. Certificate obtained from the Ministry
              of Education – the National Centre for Recognition and Equivalence
              of Diplomas https://www.cnred.edu.ro/ 5. Baccalaureate/High school
              Diploma (valid in Romania) - certified translation into Romanian;
              CHECK THE LIST OF DIPLOMAS THAT ARE VALID IN ROMANIA (ANNEX 7) The
              candidates who have passed the Baccalaureate examination in the
              sessions corresponding to the school year 2022-2023 may submit,
              instead of the Baccalaureate / High-School Diploma, a certificate
              issued by the high school, obligatorily specifying the grade point
              averages obtained during the years of study, the validity term of
              the certificate and the fact that the Baccalaureate diploma was
              not issued - certified translation into Romanian; 6. High School
              Grade Record (school transcript with grades for all high school
              years) – certified translation into Romanian (the subjects such as
              Biology, Physics, Chemistry, Physics-Chemistry, Life Sciences,
              Mathematics should be found in the school transcript); 7. Romanian
              citizens residing abroad must provide proof of permanent residence
              abroad: Romanian passport with domicile abroad/ID or certificate
              from the City Hall or Prefecture of the city of domicile -
              Romanian translation legalized by a notary; 8. Birth certificate –
              certified translation into Romanian; 9. A health certificate
              stating that the candidate to be accepted to studies does not have
              any contagious diseases or any other diseases incompatible with
              the medical profession - certified translation into Romanian; 10.
              Valid passport / identity card – scanned document in a PDF format;
              UMFCD: cod fiscal: 4192910, cont: RO57TREZ70220F330500XXXX, banca:
              TREZORERIE sect. 2 tel: +40.21 318.0719; +40.21 318.0721; +40.21
              318.0722 UMFCD: cod fiscal: 4192910, cont:
              RO57TREZ70220F330500XXXX, banca: TREZORERIE sect. 2 tel: +40.21
              318.0719; +40.21 318.0721; +40.21 318.0722 11. Proof of payment
              for the non-refundable file processing fee of RON 1,000 to be paid
              into the account below: by bank card, through an online payment
              processor, in the admission platform.
            </p>
          )}
        {selectedSubOption.subOptionKey === "sub4" &&
          selectedSubOption.parentTitle ===
            "Admission Process for English Programs" && (
            <div>
              <p>
                Selection criteria ANNEX 6 The hierarchy of the candidates shall
                be drawn up in the descending order of the score obtained and
                the provisional lists with the potentially admitted candidates
                shall be posted on the university website (www.umfcd.ro). The
                provisional list of admitted candidates is not equivalent to the
                enrollment in the 1st year of studies. The enrollment of the
                admitted candidates is conditional upon fulfilling the following
                requirements: - submitting the entire file (all the documents
                from the platform in hardcopy), the high school diploma in the
                original (or a notary statement, in Romanian, specifying the
                date when the high school diploma in the original shall be
                submitted - certified translation into Romanian) and the
                certificate of linguistic competency; - fulfilling the legal
                conditions for enrollment, including the recognition and
                equivalence of the high school studies by the Ministry Education
                in Romania; - signing the study contract and paying the
                financial obligations. The admitted candidates must confirm
                their enrollment decision, by proof of paying the tuition fee
                and signing the enrollment contract according to the schedule of
                the current Methodology.{" "}
              </p>
              <img src="/annex6.png" alt="test" />
            </div>
          )}
        {selectedSubOption.subOptionKey === "sub5" &&
          selectedSubOption.parentTitle ===
            "Admission Process for English Programs" && (
            <p>
              1.The candidate shall access the UMPCD entrance platform and shall
              upload all the mentioned documents (the selection criteria set by
              the university shall be filled in with the personal information
              required in Annex 6-which will be automatically generated by the
              registration platform, after completing it). 2.The candidates'
              files submitted online are subject to a verification by the Office
              for Foreign Students: - If the file contains all the mentioned
              documents. - If the file is complete, the candidate shall receive
              a validation email. - If the file is incomplete, the candidate
              shall receive an email through which he/she shall be asked for
              correction. Completing the files with the requested documents is
              only the candidate's obligation and must be done within the legal
              submission deadline, according to the admission calendar. A
              maximum of 3 corrections are allowed for each file. Candidates who
              apply on the last day can complete their files until 03.07.2023,
              15:00 (session I) or 28.08.2023, 15:00 (session II). Any
              correction made after the registration deadline is no longer taken
              into account.The candidate is declared eligible when the file is
              complete. The incomplete files are processed but are not eligible
              for assessment. The assessment committee, appointed by a decision
              of the Board of Trustees, verifies the files by awarding a score
              in accordance with the Assessment Grid. The enrollment in the
              study programmes of the university depends on the recognition of
              the studies by the National Centre for Recognition and Equivalence
              of Diplomas. The non-recognition by the National Centre for
              Recognition and Equivalence of Diplomas of your studies denies
              your enrollment.{" "}
            </p>
          )}
      </div>

      <BackButton displayList={displayList} setDisplayList={setDisplayList} />
    </div>
  );
}
